*&---------------------------------------------------------------------*
*& Include          ZW16_TOP
*&---------------------------------------------------------------------*


* OLE
TYPE-POOLS: OLE2.

* FUNCTION CODE
  TABLES: SSCRFIELDS.
  DATA: G_FUNCTION_KEY TYPE SMP_DYNTXT.

* EXCEL DOWN: DIRECTORY, SMW0
  DATA: GV_DIRECTORY     TYPE STRING,
        GV_INITIAL_DIR   TYPE STRING,
        GV_FILE          LIKE RLGRAP-FILENAME,
        OBJFILE          TYPE REF TO CL_GUI_FRONTEND_SERVICES.

* EXCEL DOWN: OLE
  DATA: LS_KEY LIKE WWWDATATAB.
  DATA: GO_APPLICATION  TYPE OLE2_OBJECT,
        GO_BOOKS        TYPE OLE2_OBJECT,
        GO_WBOOK        TYPE OLE2_OBJECT,
        "워크북 통합문서 기능 부여 (워크북이란 SAP내 데이터 변동시 자동 반영되는 엑셀파일)
        GO_BOOK         TYPE OLE2_OBJECT,
        GO_SHEETS       TYPE OLE2_OBJECT,
        GO_SHEET        TYPE OLE2_OBJECT, " 워크시트 기능 부여
        GO_CELLS        TYPE OLE2_OBJECT,
        GO_CELL         TYPE OLE2_OBJECT,
        GO_RANGE        TYPE OLE2_OBJECT,
        GO_FONT         TYPE OLE2_OBJECT,
        GO_ROW          TYPE OLE2_OBJECT,
        GV_PATH         TYPE STRING,
        GV_NUM          TYPE I.


DATA: BEGIN OF GS_ZSC,
        ZSTATUS   TYPE ICON-ID,
        MANDT      TYPE ZSCARR-MANDT,
        CARRID      TYPE ZSCARR-CARRID,
        CARRNAME     TYPE ZSCARR-CARRNAME,
        CURRCODE    TYPE ZSCARR-CURRCODE,
        URL    TYPE ZSCARR-URL,
        ZRESULT   TYPE CHAR200,
      END OF GS_ZSC.
DATA: BEGIN OF GS_EXCEL,
        MANDT      TYPE ZSCARR-MANDT,
        CARRID      TYPE ZSCARR-CARRID,
        CARRNAME     TYPE ZSCARR-CARRNAME,
        CURRCODE    TYPE ZSCARR-CURRCODE,
        URL    TYPE ZSCARR-URL,
      END OF GS_EXCEL.
DATA: GT_ZSC     LIKE TABLE OF GS_ZSC,
      GT_EXCEL LIKE TABLE OF GS_EXCEL.

* 엑셀 업로드

FIELD-SYMBOLS : <gt_data>       TYPE STANDARD TABLE .


* DB 데이터
*DATA: GT_DOMAIN   TYPE TABLE OF DD07T.
*
*DATA: GS_DOMAIN     LIKE LINE OF  GT_DOMAIN.
DATA: GT_ZSCARR TYPE TABLE OF ZSCARR,
      GS_ZSCARR TYPE          ZSCARR.

* 데이터 저장
*DATA: LT_ROW TYPE LVC_T_ROID,
*      LS_ROW TYPE LVC_S_ROID.

* 기타
DATA: OK_CODE   TYPE SY-UCOMM,
      GV_TITLE  TYPE SY-TITLE.

* ALV 관련
*DATA: GO_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER,
DATA : GO_CUSTOM TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_GRID    TYPE REF TO CL_GUI_ALV_GRID.
DATA : GT_FCAT   TYPE LVC_T_FCAT,
       GS_FCAT   TYPE LVC_S_FCAT,
       GS_LAYOUT TYPE LVC_S_LAYO.
*툴바 관련
DATA: fcode    TYPE TABLE OF sy-ucomm,
      wa_fcode TYPE sy-ucomm.

DATA: it_zscarrcp TYPE TABLE OF ZSCARR WITH HEADER LINE,
      it_changes  TYPE TABLE OF ZSCARR WITH HEADER LINE,
      it_deletes  TYPE TABLE OF ZSCARR WITH HEADER LINE.
